# Default values for anka-build-cloud.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

controller:
  enabled: true
  version: '1.48.0'
  image: 'veertu/anka-build-cloud-controller'
  replicaCount: 2
  ingressALBHostname: false
  ingressNginxHostname: false
  ingressNginxClassName: nginx
  ingressNginxTLSSecretName: false
  ingressNginxAuthTLSSecretName: false

registry:
  enabled: true
  version: '1.48.0'
  image: 'veertu/anka-build-cloud-registry'
  replicaCount: 1
  volumeClaimUseEFS: false
  volumeClaimID:
  volumeClaimUseLocalStorage: false
  volumeClaimName: 'registry-data'
  volumeClaimCapacityStorageSize: 200Gi
  ingressALBHostname: false
  ingressNginxHostname: false
  ingressNginxClassName: nginx
  ingressNginxTLSSecretName: false
  ingressNginxAuthTLSSecretName: false

etcd:
  enabled: true
  version: '1.48.0'
  image: 'veertu/anka-build-cloud-etcd'
  volumeClaimUseLocalStorage: true
  volumeClaimName: 'etcd-data'
  volumeClaimCapacityStorageSize: 10Gi
  # nodeAffinityKey: 'topology.kubernetes.io/zone'
  # nodeAffinityValue: 'us-west-2a'
